<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PADLOck</AssemblyName>
    <RootNamespace>PADLOck</RootNamespace>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>

    <Version>1.0.0</Version>
    <Product>PADLOck</Product>
    <Description>Подготовка Android-планшетов для режима киоска</Description>
    <Authors>vvedyaev</Authors>
    <Company>vvedyaev</Company>
    <Copyright>© 2026 vvedyaev</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\background.jpg" LogicalName="background.jpg" />
    <None Include="tools\**" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
    <None Include="profiles\**" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
    <None Include="wiki\**" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
  </ItemGroup>

</Project>
